version: '3'

services:
  tzstartups-api:
    image: tzstartups-api
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: tzstartups-api
    working_dir: /var/www/html
    ports:
      - "1943:80"
    volumes:
      - .:/var/www/html/
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - tzstartups-api-network
    depends_on:
      - tzstartupsdb

  tzstartupsdb:
    image: postgres:13.4
    container_name: startupstz-db
    restart: unless-stopped
    # ports:
    #   - "9134:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - tzstartups-api-network
    volumes:
      - tzstartups_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  tzstartups_pgdata:
    driver: local

networks:
  tzstartups-api-network:
    driver: bridge
